#!/bin/bash

tempfoo="sqlimport"
# Let's try mktemp for output, if creation fails -> Exit with Errorcode 1
TMPFILE=`mktemp /tmp/${tempfoo}.XXXXXX` || echo "ERROR: while creation of temp file!"; exit 1

# delete all lines in existing table, they are probably old
echo "TRUNCATE TABLE tlspolicies;" > $TMPFILE

# for each line in tls_policy-dane file
while read p; do
	if [[ $p != \#* ]]; then
		# if it's not a comment build a sql statement
		stringarray=($p)
		NEW="insert into tlspolicies (domain, policy, params) values ('${stringarray[0]}', '${stringarray[1]}', '${stringarray[2]}');"
		echo $NEW >> $TMPFILE
	fi
done <./tls_policy-dane

# now this script echoes to a tempfile generated by mktemp which should be usable as sql import

echo "SQL-Statements ready in file: $TMPFILE\n You can import the statements with:\n
		mysql -u USER -p vmail < $TMPFILE"
exit 0
